spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/graddaan?createDatabaseIfNotExist=true
    username: ${DB_ROOT}
    password: ${DB_PASSWORD}
  jwt:
      secret: ${JWT_SECRET}
      accessTokenExpiration: 300 # 5 mins
      refreshTokenExpiration: 604800 # 7 days 
logging:
  level: 
    org:
      springframework:
        security: DEBUG
  
  
